### ISSUE TITLE
Not all challenges seem to show up in Windows

### ISSUE THREAD

**Issue by CamiloMM** [maxogden/bytewiser#18]
The [nodeschool.io](http://nodeschool.io/) screenshot looks like this:

![screenshot](http://nodeschool.io/images/bytewiser.png)

But mine looks like this:

![administrador console - bytewiser](https://cloud.githubusercontent.com/assets/2404138/3235669/f9d659da-f0d4-11e3-8ebf-7540fa98ee48.png)

Is there anything wrong? I'm on Win7 x64, `bytewiser@2.0.0`, `npm@1.4.13`, `node@v0.11.13`

**Comment by tdd** [comment]
Hey @CamiloMM. The screenshot is overly ambitious :wink: The problems you see are indeed the ones currently implemented, regardless of platform. A recent PR, dealing with FR L10n, also updates the screenshot to only display currently-implemented problems.

@maxogden you probably want to close this one.
